# Generated by Django 3.2.12 on 2022-04-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecgwebsite', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ege',
            new_name='age',
        ),
    ]
